# This file is used for editing anything you may want to change in the bot. After making changes, restart the bot for them to take effect.



# BASIC SETTINGS
# These settings must be modified by you in order for the bot to function.

# Discord bot token
bot-token: XXX

# Server ID that the bot is being used in
# Used to register guild commands in the correct guild
main-server-id:
- 000000000000000000

roles:

  # Any users with these roles will be able to delete and edit any tag
  # NOTE: Do not leave empty. Set to 0 to disable.
  moderator: [000000000000000000]

  # Any users with these roles will be able to create tags and edit and delete their own tags. You must include all roles
  # NOTE: Do not leave empty. Set to 0 to disable.
  tagCreator: [000000000000000000]

  # Any users with these roles wont be able to create any tags.
  # NOTE: Do not leave empty. Set to 0 to disable.
  tagCreationBlacklist: [000000000000000000]





# ADVANCED SETTINGS
# These settings can be modified if you wish.

# The max length allowed for the tag name/identifier
nameMaxLength: 15

# The max length allowed for the tag message
messageMaxLength: 1000


  